site:
  url: https://catcode.me
  title: 🎉catcodeme's blog
  #start_page: start/start.adoc

content:
  branches: [HEAD]
  sources:
    - url: git@github.com:CatCodeMe/catcodeme.github.io.git
      edit_url: ~
      start-path: docs

ui:
 bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
 supplemental_files:
  - path: ui.yml
    contents: |
        static_files: [ .nojekyll ]
  - path: .nojekyll

runtime:
  fetch: true

asciidoc:
  attributes:
    page-pagination: ""

output:
  clean: true
