site:
  url: https://catcode.me
  title: 🎉catcodeme's blog
  start_page: start.adoc

content:
  branches: [HEAD]
  sources:
    - url: git@github.com:CatCodeMe/catcodeme.github.io.git
      edit_url: ~
      start-path: docs

ui:
  bundle:
    url: ./ui/ui-bundle.zip
    snapshot: true

runtime:
  fetch: true

asciidoc:
  attributes:
    page-pagination: ""

output:
  clean: true
