# 书架数据

[[items]]
title = "潜规则"
type = "book"
status = "reading"
summary = "揭示社会运行的潜规则，视角有些狭隘"
description = """
这本书里使用了比较多古代的历史案例, 试图揭示社会运行的潜规则, 但是视角有些狭隘,符合成书的 2000 年代初期的政治气候
"""
tags = ["历史", "社会学", "中国历史", "政治", "文化", "社会规则", "制度分析"]
identifier = "9787506331744"
rating = 7.1
progress = 20
startDate = "2025-10-25"
order = 1
coverImage = "/src/assets/shelf/1_qian_gui_ze.png"
sourceUrl = "https://book.douban.com/subject/1025723/"
links = ["igv0", "o2yb"]

[[items]]
title = "雪国"
type = "book"
status = "read"
summary = "名不副实的劣质作品"
description = """
可能是翻译的问题, 全书读完回味了几天，再来评价这本书, 也还是只能给个5 分。
除了偶有的几处风景描写、对恋爱脑驹子行为的刻画很生活化之外，没有其他亮点。
这本书就像川端康成在给你讲他做的梦, 作者本人沉浸其中, 读者感受却是莫名其妙，很难入戏。
切入点也很奇怪是一个出轨中年人的视角, 文中的火车似乎也有这种隐喻。我个人也很难理解日本艺妓的地位，想来不会很高，给女主这样一种身份，难道是什么恶趣味？
总之和诺奖级的期待相差太远，目前的 70% 左右的推荐度还是高了
"""
tags = ["文学", "日本文学", "小说", "川端康成", "诺贝尔文学奖"]
rating = 5.3
progress = 100
startDate = "2025-11-03"
order = 2
coverImage = "/src/assets/shelf/2_xue_guo.png"
sourceUrl = "https://book.douban.com/subject/1007305/"

[[items]]
title = "动物农场"
type = "book"
status = "read"
summary = "经典的政治寓言小说"
tags = ["文学", "小说", "政治", "反乌托邦", "乔治·奥威尔", "英国文学", "寓言"]
rating = 9.3
progress = 100
order = 3
sourceUrl = "https://book.douban.com/subject/1002385/"
